name: platform
group:
  - operations_center
  - operator_console
  - repograph
  - protocolwarden.github.io
  - switchboard
  - platformdeployment
  - custodian
  - cxrp
  - executorruntime
  - sourceregistry
  - rxp
  - platformmanifest
